---
site_name: Pizza
site_url: https://claha.github.io/pizza/
repo_url: https://github.com/claha/pizza/

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
